export const trainees = [
  {
    id: "cb8e577356799a15e5eb6bec01668dc3",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "notDefined",
    email: "alexanhambarcumyan@gmail.com",
    education: "Shushi Technology university",
    workExperience: "AIPC",
    trainings: "RELQ school",
    imagePath: "../img/",
  },
  {
    id: "92036d229a85fead88036cb59c717b3b",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "RELQ",
    imagePath: "../img/",
  },
  {
    id: "d2fe7822bf0cf0299804ea41badacf19",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "notDefined",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "../img/",
  },
  {
    id: "8bee36ff52202680b11d08858599b157",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "notDefined",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "f3c6dd2c79c25ec6fdac374ae5133062",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "notDefined",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "../img/",
  },
  {
    id: "f833ebc1630af0f8b65c9a7f74625d70",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "bc3913676fb224afc339a4bf66169c49",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "97a542a1a82582aa98c93d77315568be",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "ac4b7b96a67c6688b8ab2aa34551a447",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "f1e31008d4dd8ff0d180f66d4736c477",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "f180ad9c2678efebddc8edbf1e5efc5d",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "notDefined",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "8c4d35dbcb278a7586506ee937b4cfd4",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "notDefined",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "fd9702e4c9e2d056c160fce7d56b041c",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "notDefined",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
    imagePath: "../img/",
  },
  {
    id: "d6259a9e1c19e9d9ce5a524370513cff",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "notDefined",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "../img/",
  },
  {
    id: "f8bfb7afc4a8f8b1958fcfcf2011f398",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "notDefined",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "eec1644065d6e34ba50ca742dbd99c04",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "notDefined",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "c660f1d87838b0dfd86adf7a281dc4d7",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "notDefined",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "-----",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "../img/",
  },
  {
    id: "a14b5c5855260756b34accf3d08cca59",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "notDefined",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "e23238bd3eadb07debd3e4629e274a48",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "notDefined",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "e3964f5dcaa53149c37ddaeffb7db9f9",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "bc5247cba09314608db273c91d831969",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "e6bf77ef6ef0db33ec0795af14a3e1cd",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "notDefined",
    email: "martirosyant01@mail.ru",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "../img/",
  },
  {
    id: "d87f21ab9811405cfe766d20367648b7",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "../img/",
  },
  {
    id: "b7777b5ada8e3c8ca9ed1a2f6ef62e74",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "../img/",
  },
  {
    id: "e59690c31c897f06ab5beef1881ffebe",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "../img/",
  },
];
